language: node_js
node_js:
 - "node"

cache: yarn

script: PUBLIC_PATH='thingy-client-purple' yarn build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
